Questão 1

In [4]:
import numpy as np

In [7]:
array_uns = np.ones(8, dtype=int)
array_aleatorio = np.random.randint(0, 10, size=8)
array_soma = array_uns + array_aleatorio

soma_total = array_soma.sum()

if soma_total >= 40:
    matriz_reshape = array_soma.reshape(4, 2)
else:
    matriz_reshape = array_soma.reshape(2, 4)

print(matriz_reshape)

[[ 2  3  4 10]
 [ 8  4  3  1]]


Questão 2

In [43]:
campo = np.zeros((2, 2), dtype=int)
linha_bomba = np.random.randint(0, 2)
coluna_bomba = np.random.randint(0, 2)
campo[linha_bomba, coluna_bomba] = 1

total_posicoes_seguras = campo.size - 1
posicoes_acertadas = set()
jogadas = 0
jogo_ativo = True

print("Escolha uma posição (0 ou 1).\n")

while jogo_ativo:
    linha = int(input("Linha (0 ou 1): "))
    coluna = int(input("Coluna (0 ou 1): "))
    jogadas += 1

    if (linha, coluna) == (linha_bomba, coluna_bomba):
        if jogadas <= 3:
            print("Game Over! :( Try Again!")
        jogo_ativo = False
    else:
        posicoes_acertadas.add((linha, coluna))
        print(f"Posição segura! ({len(posicoes_acertadas)}/{total_posicoes_seguras})\n")
        if len(posicoes_acertadas) == total_posicoes_seguras:
            print("Congratulations! You beat the game! :)")
            jogo_ativo = False

Escolha uma posição (0 ou 1).

Linha (0 ou 1): 1
Coluna (0 ou 1): 0
Posição segura! (1/3)

Linha (0 ou 1): 0
Coluna (0 ou 1): 1
Posição segura! (2/3)

Linha (0 ou 1): 0
Coluna (0 ou 1): 0
Posição segura! (3/3)

Congratulations! You beat the game! :)


Questão 3

In [19]:
matriz_q3 = np.random.randint(0, 10, size=(3, 5))

qtd_linhas, qtd_colunas = matriz_q3.shape

total_elementos = qtd_linhas * qtd_colunas
print(f"Linhas x colunas = {total_elementos} elementos")

if total_elementos % 2 == 0:
    print("A matriz poderia se tornar um vetor unidimensional com número PAR de elementos.")
else:
    print("A matriz poderia se tornar um vetor unidimensional com número ÍMPAR de elementos.")

Linhas x colunas = 15 elementos
A matriz poderia se tornar um vetor unidimensional com número ÍMPAR de elementos.


Questão 4

In [25]:
np.random.seed(10)
matriz4x4 = np.random.randint(1, 51, size=(4, 4))

media_linhas = matriz4x4.mean(axis=1)
media_colunas = matriz4x4.mean(axis=0)
print("Média de cada linha:", media_linhas)
print("Média de cada coluna:", media_colunas)

maior_media_linha = media_linhas.max()
maior_media_coluna = media_colunas.max()
print(f"Maior média entre as linhas: {maior_media_linha}")
print(f"Maior média entre as colunas: {maior_media_coluna}")

valores, contagens = np.unique(matriz4x4, return_counts=True)
print("\nQuantidade de aparições de cada número gerado:")
for valor, contagem in zip(valores, contagens):
    print(f"  Número {valor}: {contagem} vez(es)")

numeros_duas_vezes = valores[contagens == 2]
print("\nNúmeros que aparecem 2 vezes:", numeros_duas_vezes)

Média de cada linha: [16.   33.75 34.5  23.75]
Média de cada coluna: [29.75 24.25 33.75 20.25]
Maior média entre as linhas: 34.5
Maior média entre as colunas: 33.75

Quantidade de aparições de cada número gerado:
  Número 1: 2 vez(es)
  Número 9: 1 vez(es)
  Número 10: 2 vez(es)
  Número 16: 1 vez(es)
  Número 26: 1 vez(es)
  Número 29: 1 vez(es)
  Número 30: 2 vez(es)
  Número 37: 1 vez(es)
  Número 41: 1 vez(es)
  Número 43: 1 vez(es)
  Número 49: 1 vez(es)
  Número 50: 2 vez(es)

Números que aparecem 2 vezes: [ 1 10 30 50]


Questão 5

In [32]:
zeros_3x3 = np.zeros((3, 3))
uns_3x3 = np.ones((3, 3))

soma_matrizes = zeros_3x3 + uns_3x3
print("Soma:")
print(soma_matrizes)

escalar = 5
resultado_escalar = soma_matrizes * escalar
print(f"\nResultado multiplicado pelo escalar {escalar}:")
print(resultado_escalar)

vetor_final = resultado_escalar.reshape(9)
print("\nArray unidimensional de 9 elementos:")
print(vetor_final)

Soma:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Resultado multiplicado pelo escalar 5:
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

Array unidimensional de 9 elementos:
[5. 5. 5. 5. 5. 5. 5. 5. 5.]


Questão 6

In [30]:
array_arange = np.arange(10, 31, 2)

maior_valor = array_arange.max()
indice_maior = array_arange.argmax()
menor_valor = array_arange.min()
indice_menor = array_arange.argmin()
soma_total = array_arange.sum()

print(f"Maior valor: {maior_valor} (índice {indice_maior})")
print(f"Menor valor: {menor_valor} (índice {indice_menor})")
print(f"Soma: {soma_total}")

Maior valor: 30 (índice 10)
Menor valor: 10 (índice 0)
Soma: 220


Questão 7

In [31]:
np.random.seed(7)
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

array_concatenado = np.concatenate((array1, array2))
print("Array concatenado:", array_concatenado)

matriz_2x5 = array_concatenado.reshape(2, 5)
print("\nMatriz com 2 linhas e 5 colunas:")
print(matriz_2x5)

Array concatenado: [ 5 10  7  4  4  8  8 10  8  9]

Matriz com 2 linhas e 5 colunas:
[[ 5 10  7  4  4]
 [ 8  8 10  8  9]]
